name: fitness_531
description: A new Flutter project.

version: 1.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2 # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^0.5.1
  cloud_firestore: ^0.9.13
  rect_getter: ^0.0.1 # To get the FAB position so we can add ripple effect on records page
  percent_indicator: ^1.0.16
  intl: ^ 0.15.8 # For date time
  dynamic_theme: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: false
  ios: true
  image_path: "assets/barbell_ios.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is included with your application
  uses-material-design: true
  assets:
    - assets/bench.png
    - assets/deadlift.png
    - assets/press.png
    - assets/squat.png
    - assets/barbell_raw.png # For using in the side drawer


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
