* 5/3/1 Fitness

#+html:<a href="https://codemagic.io/apps/5cdc80965c71630019441043/5cdc80965c71630019441042/latest_build"><img src="https://api.codemagic.io/apps/5cdc80965c71630019441043/5cdc80965c71630019441042/status_badge.svg" /></a>

I wrote the app to learn flutter mostly, also the app allows me to
track my 5/3/1 Boring But Big Strength Training Regimen. I don't think
I have followed all the security practices while storing your training
numbers in the cloud, hence I am not selling the app. If you want to
build this for yourself get your own firebase account, which is free
upto 1 GB of data.

** Icons I should pay respects too
- https://icons8.com/icon/38915/deadlift
- https://icons8.com/icon/13386/bench-press
- https://icons8.com/icon/16962/squats
- https://icons8.com/icon/16971/weightlifting

Main icon: https://www.flaticon.com/free-icon/barbell_1690609#term=barbell&page=1&position=23

** App icons are made like this
For i-OS
https://pub.dartlang.org/packages/flutter_launcher_icons

For Android
Icons are made with Android Studio, so they look native based on android versions . [[https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html][Adaptive icons]]

On android, every size of the splash screen image name
=ic_launcher.png= is just the raw image(same size), just so the icon
splash screen is bigger.

** To get firebase config
First add the fingerprint for the new system to firebase and download the new google-services.json file

Add the projects fingerprint on the new system using this method https://developers.google.com/android/guides/client-auth

For Android: https://console.firebase.google.com/u/1/project/fitness-531/settings/general/android:com.kaipada.fitness_531
- put the =json= file under android/app/google-services.json
  
** References
- https://exrx.net/WeightTraining/Powerlifting/531
- https://medium.com/flutter-community/simple-recipes-app-made-in-flutter-firebase-and-google-sign-in-14d1535e9a59
** TODOs
- [ ] Update the records page so, when deleting a record it animates it
- [ ] Update the records page so, user can undo deletion ?
- [ ] Add a settings page and move the less used stuff there
- [ ] Add a chips section to add and remove plates available in the Gym
- [ ] Add time series graphs to show records progress
- [X] +Update database schema+ Idea is good but don't wanna copy the data now, will keep this in mind for the future
 #+begin_src txt
 # Current database schema
 /{table}/{collection}/{user_id}/{document_id_auto_generated}
 /users/max_reps/xfdlisjdlskjdloshdwlkb/-LfbG5FoshW1l0V6hfjv

 # New better schema
 /{table}/{user_id}/{collection}/{document_id_auto_generated}
 /user/sdlksjdlsfhqefbqedfjbnq/records/KMbSCgDsNutZLejnEniR
 #+end_src
** Notes

#+begin_src sh
# launch emulator on linux
sudo chown justin /dev/kvm
emulator -avd Pixel_2_API_26
emulator -avd Pixel_2_API_29
#+end_src
